### ISSUE TITLE
"Export Patch" does nothing in Local Storage view in Windows version. 

### ISSUE THREAD

**Issue by matreve** [meanmedianmoge/zoia_lib#102] opened 2021-07-01 01:58 UTC
**Describe the bug**
"Export Patch" does nothing in Local Storage view. No dialog appears asking to select the patch slot. 

**Desktop (please complete the following information):**
 - OS: Mac OS , Windows 10
 - Version 1.1

**Additional context**
This functionality has a bug in Mac version too. It does display a window asking for the destination slot, but then refers to the wrong folder when making determination whether the slot is empty or not.

**Comment by meanmedianmoge** [comment] 2021-07-01 02:40
https://user-images.githubusercontent.com/51132973/124056601-0986aa00-d9f4-11eb-8e59-397fe152458e.mov

Downloaded the 1.1 Mac zip and attempted to export - can't seem to replicate the bug.

**Comment by matreve** [comment] 2021-07-01 03:09
Not sure what to tell you. The app behaves very differently. It claims that the slots are taken even though they are not. It is not clear which folder it selects as the export destination at all. Very generally speaking, I think the problem is that your system seems to not be very representative and reliable as a test environment.

**Comment by meanmedianmoge** [comment] 2021-07-01 03:16
Could you provide some screenshots or video of the attempts you’ve made so far?

The prompts for export should denote the destination directory and slot, though you did mention before that no dialog box showed up.

I’ll poke around the code to try and understand why this is happening.

**Comment by matreve** [comment] 2021-07-01 03:21
Since clicking on "Export Patch" does nothing, what is there for me to
screenshot that could be useful? All you'll see is the view of the
Librarian.

**Comment by meanmedianmoge** [comment] 2021-07-01 12:50
Some things that might be helpful to rule out:
- SD lock tab is down (dumb, but it happens)
- Invalid patches in the backend to export (requires checking in on the directories in `/Users/user/Library/Application Support/.ZoiaLibraryApp` for Mac, and the same location as you checked in #99 for Windows)
- Other buttons in the app function, like do all of them cause issue or just a couple?

**Comment by matreve** [comment] 2021-07-01 19:02
No. I’m using the card without a full size SD card adapter on PC and Micro SD has no write protect tab. On Mac it is in the adapter but the tab is in the correct state. 

There are no invalid patches. 

Other buttons work more reliably but not 100% either, there are many other small glitches and inconsistencies.

**Comment by meanmedianmoge** [comment] 2021-07-01 19:27
I think I figured it out, but it requires that the SD location is pulled before app closure. On shutdown, it will attempt to collect a bunch of preferences (like the UI sizes, SD card, dark mode, etc). If there is no SD location saved from that process or the SD is absent during init, it won't have a location to use and the Export button will fail. The steps I took were the following:

- (make sure SD is not inserted) Open app, close app to reset the SD preferences
- Open app, insert SD
- Either navigate to the SD tab, set the location from the Files menu, or attempt to export (without setting the location)
- During any of the above prompts, set the SD
- Export from Local Storage (and banks) should now work

The fix is pretty straightforward in terms of coding, will try to update the zip shortly. For now, let me know if those steps work.

**Comment by matreve** [comment] 2021-07-01 19:38
Nope, sorry. I followed all the steps. It does not work. Still the prompt
to select the destination slot on SD card does not appear when I click on
"Export Patch". Nothing happens.

**Comment by meanmedianmoge** [comment] 2021-07-01 19:41
Try setting the SD a different way?

**Comment by matreve** [comment] 2021-07-01 20:05
So the first time I set the SD path was using the File menu. After you sent
the above message I repeated all the steps from scratch and tried to set it
as per your instruction, by:  "attempt to export (without setting the
location)". Clicking on "Export Patch" did not bring the prompt to set the
SD card path. In this case also nothing happens.

So I tried another method of setting the SD path by simply clicking on the
SD Card View tab. This did bring the prompt to set the SD card path. I set
it but unfortunately this did not cure the behavior - clicking on Export
Patch does nothing.

**Comment by meanmedianmoge** [comment] 2021-07-01 20:49
Apologies about the "attempt to export" option for the setting the SD, I had tried that after making the code fix. The other 2 methods of SD location should work though, so I'm effectively stumped. You can roll back to 1.0 if this is crucial or wait for the new zip with the bugfix. Thanks for experimenting a bit.

**Comment by matreve** [comment] 2021-07-02 02:34
I have to say that these bugs are obviously bugs that need to be fixed
regardless but what the real problem is in my opinion, is the very unclear
workflow and operation of the app. It's a true mess, believe me.  There are
many seemingly similar meanings, names and operations throughout the patch
which are not the same, or are not the same in a given context but the same
in the other. When setting SD card location, it is not clear which folder
on it will be used for exports. Even your instructions for troubleshooting
don’t mention the need to additionally specify Set Export Directory, and
I'm unclear whether this is needed or not (but I checked when
troubleshooting the bug every possible combination). It is unclear if
specifying just the SD path chooses a specific folder (directory) in it as
a default, or if it needs to be specified in that step. In addition, the
prompt asks to specify a folder but when the SD card is chosen as a device,
it accepts it as a folder selection (which its root location could be
considered that I guess) but does not state explicitly which subfolder it
chose (but I know it's supposed to save the patches to the To_Zoia folder).
Then when using Set Export Directory the confirmation prompt seems to be
exactly the same, bringing the question if the specific folder selection
was respected or not and if these operations are the same and what the
difference between them is. There are many many places throughout the app
where such practice continues. It is the world’s Most Unnecessarily
Complicated Simple App. It really does start with the UI as it then creates
all the issues. BTW, clicking on any item in the list under the Help menu
also does absolutely nothing.



On Jul 1, 2021, at 4:49 PM, meanmedianmoge ***@***.***> wrote:

﻿

Apologies about the "attempt to export" option for the setting the SD, I
had tried that after making the code fix. The other 2 methods of SD
location should work though, so I'm effectively stumped. You can roll back
to 1.0 if this is crucial or wait for the new zip with the bugfix. Thanks
for experimenting a bit.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meanmedianmoge/zoia_lib/issues/102#issuecomment-872540906>,
or unsubscribe

**Comment by meanmedianmoge** [comment] 2021-07-02 12:03
Appreciate the feedback. Please see the updated Mac release here for the fix related to this bug, and for the Help items to actually display: https://github.com/meanmedianmoge/zoia_lib/releases/tag/v1.1.

I'll try to update the Windows version sometime this weekend.

**Comment by matreve** [comment] 2021-07-02 20:50
Neither Windows or Mac version seems to have been updated.

**Comment by Jmeferlater** [comment] 2021-07-03 21:09
Wasn't sure if I should open a new issue or not, but I believe I'm experiencing the same behavior on Windows as well, and I think I've figured out the root cause.

The main problem is that if the `to_zoia` folder already exists on the SD card, any attempts to load a patch from local storage onto the card will fail completely. 

This can be replicated by deleting the `to_zoia` folder, then trying to export a patch from local storage, which will actually succeed. However, on the next attempt nothing will happen - no popup windows or anything, and the patch never gets put on the SD card. 

Running latest master locally and doing the above, I end up getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\jamie\Documents\zoia-librarian\zoia_lib\zoia_lib\UI\ZOIALibrarian_local.py", line 272, in initiate_export
    os.mkdir(os.path.join(self.sd.get_sd_root(), export_dir))
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'E:to_zoia'
``` 

It seems like this is happening because the check here: https://github.com/meanmedianmoge/zoia_lib/blob/b75b2503b4d8ebf65a95aa3a6b4dcd9e69b9d9d3/zoia_lib/UI/ZOIALibrarian_local.py#L271 
always returns true.  

I believe that happens because the output of `os.listdir(self.sd.get_sd_root())` includes "to_zoia", but `export_dir` is "E:to_zoia", so the two will never be the same, always returning `true` in that conditional check.

Hopefully this was helpful. If you need any more testing on Windows let me know, I'll gladly help out.

**Comment by meanmedianmoge** [comment] 2021-07-03 22:10
Good catch @Jmeferlater, thanks for debugging! I’ll put in a patch for this soon and will update the release to reflect the change.

**Comment by meanmedianmoge** [comment] 2021-07-04 19:45
I'm pretty sure changing the os.mkdir command on line 272 to
```
os.makedirs(os.path.join(self.sd.get_sd_root(), export_dir), exist_ok=True)
```
will suffice; could either of you confirm using Windows? @Jmeferlater @john-breton

**Comment by Jmeferlater** [comment] 2021-07-07 01:51
Yup, that worked for me!

**Comment by meanmedianmoge** [comment] 2021-07-07 02:39
Perfect, thanks! The patch has been merged to master, will update the release files shortly.

**Closed by meanmedianmoge** 2021-07-07 02:39 UTC
Labels: bug, high priority

**Comment by matreve** [comment] 2021-07-11 04:39
This works if the SD card is connected BUT if it is not, there is no prompt to select the path to it, nothing happens.
