### ISSUE TITLE
The local storage view under the "Banks" not showing newly downloaded patches. 

### ISSUE THREAD

**Issue by matreve** [meanmedianmoge/zoia_lib#99] opened 2021-06-25 05:27 UTC
**Describe the bug**
The local storage view under the "Banks" not showing newly downloaded patches. 

**To Reproduce**
Click on "Patch Storage" tab. Download a patch from Patch Storage list. Click on "Banks". The downloaded app does not show in the local storage list until the Librarian is restarted. 
**Expected behavior**
I'd expect the list of patches to show all patches in the local storage, including newly downloaded ones. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by john-breton** [comment] 2021-06-25 10:53
I can't seem to replicate this in my testing. Would you happen to know which patch you had downloaded? I'm wondering if maybe it is a specific patch with a weird file extension that could be causing the issue.

**Comment by matreve** [comment] 2021-06-25 15:56
This is the patch which would not show in the local storage unless the Librarian was restarted: https://patchstorage.com/ooh-yaas/ There were other patches which acted the same, but I don’t remember their names. It is true that the behavior is inconsistent, that is that sometimes Librarian works as expected.

**Comment by meanmedianmoge** [comment] 2021-06-25 16:25
What version of the app are you running? That patch in particular downloads and shows in Banks and Local Storage fine for me, should just be a singular binary file.

**Comment by matreve** [comment] 2021-06-25 16:34
It’s the latest version I downloaded yesterday here. V1.1

**Comment by meanmedianmoge** [comment] 2021-06-26 15:30
Can you provide a screenshot of the files in this location: `C:\Users\user\AppData\Roaming\.ZoiaLibraryApp\`? That's the local backend which includes all the necessary files and directories that are referenced when populating the Local and Bank tabs.

**Comment by matreve** [comment] 2021-06-27 04:13
This looks like a Mac file system. I'm on Windows 10. Not sure where to
look for this folder.

**Comment by matreve** [comment] 2021-06-27 04:23
My bad, here is the screenshot. I'm experiencing this issue of the patches
missing even after I restart the app. Some patches are visible in "Local
Storage" but not in the "Banks". Since I can't re-download it from
Patchstorage because the Librarian tells me it's been downloaded already, I
can't put in on the SD card using Librarian.

**Comment by meanmedianmoge** [comment] 2021-06-27 14:29
All looks pretty normal to me. If you have time to poke around each of those folders, could you identify any that include either a separate directory or a .zip file? Basically it’s expected that those numbered folders will only have .json and .bin files, and anything else will cause the patch to not display due to an error. Getting those numbers (which are unique patch id’s) will help us identify the issue.

**Comment by matreve** [comment] 2021-06-28 19:04
So 90% of those folders have a .bin file and a .json file. There are some which have two pairs which I assume are versions of the patch. One folder however has a .zip folder inside and nothing else. It is not possible to unzip it. 
![Screenshot (490)](https://user-images.githubusercontent.com/57880522/123690163-0fc52c80-d822-11eb-9188-0a15d60bf099.jpg)

**Comment by matreve** [comment] 2021-06-28 22:02
I deleted it and even though it’s not the patch that wasn’t showing, it made the patch I could not get to show in the “banks” view’s local storage section show (Anagramophone patch), or maybe it is coincidence. There are many other bugs related to the “banks” tab and its operations (mostly drag and drop functionality is really a hit or miss, sometime doing weird things) but I’ll hopefully have time to post it as a separate issue here. I’m thinking about moving Librarian to my Mac and see if it works better there.  

As a side note, the functionality which seems pretty basic and useful but apparently missing is ability to see the card contents view and local view side by side in one tab. This would allow very easy update of an existing patch in card’s folder with a newer version (or any modification of existing folder/bank on a card for that matter). Here the only way of doing it is by replacing entire folder/bank, and since these can’t be imported from the card, one has to rely on locally saved version of such folder and update that instead. However, to make things worse, such copy is not automatically saved locally when exporting folders/banks to the card, so sometimes it does not even exist (exists only if Save function is used at the time of exporting folder/bank to the card). Very simple and basic functionality (at the end of the day it is about moving things between card and local storage) now requires complicated workarounds.

**Comment by john-breton** [comment] 2021-06-29 11:21
I'm glad to hear the other patches have appeared. We had known about this bug previously, should a patch fail to decompress it can cause some abnormal behaviour in the other views. The problem is now figuring out why the patch did not decompress because that should not have happened in the first place. I suspect meanmedianmoge may have been correct that the connection to the site was interrupted at some point, although that might require a bit more experimentation on our part.

I'm a bit confused about the importing/exporting comment. There's an option to import multiple patches from a folder that is already present in the Librarian and there's also the ability to export individual patches to the slot of your choice. Replacing the entire contents of the SD card isn't required if you want to make a single patch change, you could just export the patch you want to the desired slot from the Local Storage View. That being said, I can still see the benefit of adding what you had suggested, and it may be something we could consider for the next update. 

I think I may just be confused though, are you referring to the fact that Banks cannot be imported from an SD card and saved into the Librarian? Something like that may be possible to add as a feature, but the actual implementation of that is a bit more complex than one might expect (what happens if the patches that are a part of a Bank that are being imported already exist in the Librarian? Or if they are modified compared to what exists, so a Version History would need to be created, etc.).

**Comment by meanmedianmoge** [comment] 2021-06-29 13:41
@matreve Glad to hear that deleting the problematic file has shown the other patches!

Couple of notes on your comments:
- Drag and drop being hit-or-miss is documented here: https://github.com/meanmedianmoge/zoia_lib/issues/93. It's not easy to diagnose, so more reports on when it occurs (step-by-step) would be helpful.
- There's also my internal monologue about Banks (we're renaming them "Folders" from now on) vs Version Histories and how we might handle them that you can read here as well: https://github.com/meanmedianmoge/zoia_lib/issues/83. Like I say in the ticket and along similar lines as @john-breton mentions.. it's a deceptively complex problem.

We'll take a look at the decompression code, will close this for now. If it happens again, feel free to re-open.

**Closed by meanmedianmoge** 2021-06-29 13:41 UTC
Labels: bug, high priority

**Comment by matreve** [comment] 2021-06-29 20:17
I'll make a video capture of the app because it seems to me it behaves
nothing like what you are presenting. Thanks.

**Comment by matreve** [comment] 2021-06-29 20:38
How exactly is this accomplished: " if you want to make a single patch
change, you could just export the patch you want to the desired slot from
the Local Storage View" ?? Clicking on Export Patch in Local Storage View
does nothing. BTW, the last two columns on the right in Local Storage View
( Export Patch and X columns) didn't show in the interface, it needed to be
scaled - this was adding to my confusion as I didn't see these options. But
now that I see them, Export Patch does nothing.

In Banks view: reorganizing patches in the Bank by dragging it to a
different slot causes this patch to be duplicated, not moved. Attempting to
move it again to another slot repeats the behavior. After a few attempts of
moving the patch the bank becomes populated with the copies of that patch.
These copies have no X next to them.
